# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=pypy

install: pip install -U tox

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: joschaKrutzki
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: joka/deform_markdown
    condition: $TOXENV == py27
