deploy:
  provider: pypi
  user: joschaKrutzki
  password:
    secure: s6WYq0YrhU/8cVZt3KfFQj9tFjjc+163zF/kbizaDP6uwl+NPv0RmxsWxKLbekrApEqnh/9AF9cRqgUvOWKG+OnzlZj0a6Ge1sVY/1wcunPunWaUZeDSspC31mXPk9kG9ny1VXkZqX1Rf5ts8GhbQ3kiw2rnVzsksfHM3bjI5jQUvmsxaDTToSMrBJDlY584BWiP+QDYE2Ix2d5hwlqiMbejPjYFYK7wjw4wn8p+XUEW0gvj17ujou7zhdF3FiyrvFLaIyrt1rePV2k7XKBakvIODuu3VgdO05hKhJV4GG+CLQb6yr9gqHO8haPAoUmOjAHPThkcRNkCBscRz3fSnbiagd5jbuyGuP0/ENvvm590xs+Zj777WnKv0ExT1MYb0UpbzLw/G1DSkazMgdyZ14Bl+bqpBWSaOkKuc5PpERwEqXGkxuIZEO5UD6yJOFRWjvzft2nfextfLDJMB2d0NgDJzIoXvNM4r0wbEDGr83ljqUIs3pvXIdcjLSsTobAmMlzp3GPg+WyxTtfcNS27B11UVlYutZRqLlIksi2VUxCSq6+T3YdjFIFDBJsKDU3CcARbkHyJnjS6ngx3tfX+bfUQnFe68VahzOFayqxsiDS80EoNEru257Uv3k5XPTmVouas4s/nZw/VgRBcTtp/y35z06Fw9OxxUo4KaAZcwNc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: liqd/deform_markdown
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py27
install: pip install -U tox
language: python
python: 3.5
script: tox
